### ISSUE TITLE
Transition starts working only after second execution

### ISSUE THREAD

**Issue by davdroman** [davdroman/swiftui-navigation-transitions#118]
### Discussed in https://github.com/davdroman/swiftui-navigation-transitions/discussions/117

<div type='discussions-op-text'>

<sup>Originally posted by **izombieprod** December 19, 2023</sup>
Every time after building the application, the first transition is the default slide every time. Your animation is applied only after you call those views one time with default transition animation. Do you know what I'm doing wrong? </div>

**Comment by davdroman** [comment]
@izombieprod are you using the latest version of the library (0.13.3)?

If so, please provide a minimal reproducible project that can help me get started debugging the issue.

**Comment by izombieprod** [comment]
Hi! Yes, I'm using 0.13.3 

here's an example of code with an issue: 

`
import SwiftUI
import NavigationTransitions

struct SplashScreenView: View {
    @StateObject var viewModel: SplashScreenViewModel
    
    @EnvironmentObject var coordinator: Coordinator
    
    @State private var isVisible = false
    
    typealias ViewModel = SplashScreenViewModel
    
    var body: some View {
        NavigationStack(path: $coordinator.steps) {
            ZStack {
                GradientBackgroundView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                
                Image(Constants.logos.splashScreen)
                    .transition(.move(edge: .leading))
            }
            .navigationDestination(for: ScreenModel.self) { screen in
                switch screen.type {
                case .login:
                    GetStartedView(viewModel: GetStartedViewModel())
                        .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                case .swipesExpandedView:
                    if let screen = screen as? SwipesExpandedViewScreenModel {
                        FullScreenDetailView(card: screen.card)
                            .navigationTransition(.zoom)
                            .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                            
                    } else {
                        EmptyView()
                    }
                    
                }
            }
        }
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 1)  {
                viewModel.checkAuth { screenModel in
                    coordinator.showNextScreen(screenModel)
                }
            }
            
            
            struct DeferView<Content: View>: View {
    let content: () -> Content
    
    init(@ViewBuilder _ content: @escaping () -> Content) {
        self.content = content
    }
    
    var body: some View {
        content()
    }
}


class Coordinator: ObservableObject {
    static let shared = Coordinator()
    
    @Published var steps = [ScreenModel]()
    
    private init() {
        
    }
    
    func showNextScreen(_ screenModel: ScreenModel) {
        ///how to find where it was no main thread
//        guard Thread.isMainThread else { fatalError("current failure") }
        steps.append(screenModel)
    }
    
    
    func goBack() {
        steps.removeLast()
    }
    
    func popToRoot() {
        steps = [.init(title: "Login", type: .login)]
    }
}

class ScreenModel: Identifiable, Hashable {
    static func == (lhs: ScreenModel, rhs: ScreenModel) -> Bool {
        lhs.id == rhs.id
    }
    
    var id: String {
        type.id
    }
    
    let title: String
    let type: CoordinatorStep
    
    let navigationBarVisible = false
    
    init(title: String, type: CoordinatorStep) {
        self.title = title
        self.type = type
    }
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

class SwipesExpandedViewScreenModel: ScreenModel {
    let card: SwipeMockCard
    
    init(card: SwipeMockCard, title: String, type: CoordinatorStep) {
        self.card = card
        super.init(title: title, type: type)
    }
}

extension CoordinatorStep: Identifiable {
    var id: String {
        self.rawValue
    }
}
`

**Comment by izombieprod** [comment]
Hi! Yes, I'm using 0.13.3

here's an example of code with an issue:

`struct SplashScreenView: View {
    @StateObject var viewModel: SplashScreenViewModel
    
    @EnvironmentObject var coordinator: Coordinator
    
    @State private var isVisible = false
    
    typealias ViewModel = SplashScreenViewModel
    
    var body: some View {
        NavigationStack(path: $coordinator.steps) {
            ZStack {
                GradientBackgroundView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                
                Image(Constants.logos.splashScreen)
                    .transition(.move(edge: .leading))
            }
            .navigationDestination(for: ScreenModel.self) { screen in
                switch screen.type {
                case .login:
                    GetStartedView(viewModel: GetStartedViewModel())
                        .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                case .customizeScreen:
                    CustomizeView(viewModel: CustomizeViewModel())
                        .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                case .profilePreview:
                    PreviewProfileView(viewModel: PreviewProfileViewModel())
                        .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                case .swipesExpandedView:
                    if let screen = screen as? SwipesExpandedViewScreenModel {
                        FullScreenDetailView(card: screen.card)
                            .navigationTransition(.zoom)
                            .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                    } else {
                        EmptyView()
                    }
                    
                }
            }
        }
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 1)  {
                viewModel.checkAuth { screenModel in
                    coordinator.showNextScreen(screenModel)
                }
            }
        }
    }
}`

**Comment by izombieprod** [comment]
Hi there! Yes, Im using 0.13.3 version as spm , with your custom zoom transition (but the same bug occurs to me with any transitions, I checked) on Xcode 15. 



```
struct SplashScreenView: View {
    @StateObject var viewModel: SplashScreenViewModel

    @EnvironmentObject var coordinator: Coordinator
    
    @State private var isVisible = false
    
    typealias ViewModel = SplashScreenViewModel
    
    var body: some View {
        NavigationStack(path: $coordinator.steps) {
            ZStack {
                GradientBackgroundView()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                
                Image(Constants.logos.splashScreen)
                    .transition(.move(edge: .leading))
            }
            .navigationDestination(for: ScreenModel.self) { screen in
                switch screen.type {
                case .login:
                    GetStartedView(viewModel: GetStartedViewModel())
                        .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                case .swipesExpandedView:
                    if let screen = screen as? SwipesExpandedViewScreenModel {
                        FullScreenDetailView(card: screen.card)
                            .navigationTransition(.zoom)
                            .toolbar(screen.navigationBarVisible ? .visible : .hidden, for: .navigationBar)
                            
                    } else {
                        EmptyView()
                    }
                    
                }
            }
        }
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 1)  {
                viewModel.checkAuth { screenModel in
                    coordinator.showNextScreen(screenModel)
                }
            }
        }
    }
}
```

**Comment by izombieprod** [comment]
an here's how my coordinators is look like 

```
class Coordinator: ObservableObject {
    static let shared = Coordinator()
    
    @Published var steps = [ScreenModel]()
    
    private init() {
        
    }
    
    func showNextScreen(_ screenModel: ScreenModel) {
        steps.append(screenModel)
    }
    
    
    func goBack() {
        steps.removeLast()
    }
    
    func popToRoot() {
        steps = [.init(title: "Login", type: .login)]
    }
}

class ScreenModel: Identifiable, Hashable {
    static func == (lhs: ScreenModel, rhs: ScreenModel) -> Bool {
        lhs.id == rhs.id
    }
    
    var id: String {
        type.id
    }
    
    let title: String
    let type: CoordinatorStep
    
    let navigationBarVisible = false
    
    init(title: String, type: CoordinatorStep) {
        self.title = title
        self.type = type
    }
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

class SwipesExpandedViewScreenModel: ScreenModel {
    let card: SwipeMockCard
    
    init(card: SwipeMockCard, title: String, type: CoordinatorStep) {
        self.card = card
        super.init(title: title, type: type)
    }
}
```

**Comment by davdroman** [comment]
I'm getting a lot of errors for things that are missing from your example. Could you narrow down the reproducible scenario into a standalone project that can be zipped or put in a repo? Otherwise there are too many gaps to fill to debug effectively.

<img width="1512" alt="Screenshot 2023-12-20 at 12 02 55" src="https://github.com/davdroman/swiftui-navigation-transitions/assets/2538074/6f0653fb-c8ea-4a84-89d7-8e1a083be60d">

<img width="1512" alt="Screenshot 2023-12-20 at 12 00 56" src="https://github.com/davdroman/swiftui-navigation-transitions/assets/2538074/f62139b6-c5d0-4904-8a07-c9a4381e9df4">

**Comment by izombieprod** [comment]
i will create a test project and upload it here after work, thanks man!

**Comment by izombieprod** [comment]
https://github.com/izombieprod/swiftUItestTransitions  - here's a code example with the same transition behavior as I told you in the thread before. the first transition is always the default.

**Comment by rdsarna** [comment]
Just wanted to pop in and say that I'm facing the same issue.

**Comment by davdroman** [comment]
Thank you @izombieprod, I'll take a look at this and get back to you shortly.

**Comment by davdroman** [comment]
Oh I see what's going on. So you're tacking the `.navigationTransition` modifier to each detail view expecting them to have different transitions:

```swift
.navigationDestination(for: ScreenModel.self) { screen in
	 switch screen.type {
	 case .firstView:
		  FirstView()
				.navigationTransition(.zoom)
	 case .secondView:
		  SecondView()
				.navigationTransition(.slide)
	 case .thirdDView:
		  ThirdView()
				.navigationTransition(.default)
	 }
}
```

However, this is not a supported use case. I'm afraid you're limited to one specific transition per `NavigationStack`.

Sorry about this, but there's just no way around this. You must pick one transition and apply it to the navigation stack instead of the detail view, as follows:

```swift
NavigationStack(path: $coordinator.steps) {
  // ...
}
.navigationTransition(.xyz)
```

**Comment by izombieprod** [comment]
Understood, thanks
