### ISSUE TITLE
Error When Archive (Command SwiftCompile failed with a nonzero exit code)

### ISSUE THREAD

**Issue by iTarek** [davdroman/swiftui-navigation-transitions#90]
Only with the last update 0.10.0 my app works good when build, but when archive to submit to Appstore I got error (Command SwiftCompile failed with a nonzero exit code)

```
6.	While evaluating request QualifiedLookupRequest(0x12dd764b0 StructDecl name=NotionAppsView, {Apps.(file).NotionAppsView@/Users/itarek/Library/Mobile Documents/NotionAppsView.swift:14:8}, 'Body', { NL_ProtocolMembers, NL_RemoveNonVisible, NL_RemoveOverridden, NL_OnlyTypes })
7.	While evaluating request DirectLookupRequest(directly looking up 'Body' on SwiftUI.(file).View with options {  })
8.	While loading members for extension of View (in module 'NavigationTransitions')
9.	While deserializing 'navigationTransition' (FuncDecl @ 392035) in 'NavigationTransitions'
10.	    ...decl is named 'navigationTransition(_:interactivity:)'
11.	While deserializing '_' (OpaqueTypeDecl @ 374635) in 'NavigationTransitions'
12.	*** DESERIALIZATION FAILURE ***
*** If any module named here was modified in the SDK, please delete the ***
*** new swiftmodule files from the SDK and keep only swiftinterfaces.   ***
module 'NavigationTransitions', builder version '5.8.1(5.8.1)/Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)', built from source, non-resilient, loaded from '/Users/itarek/Library/Developer/Xcode/DerivedData/BuildProductsPath/Release-iphoneos/NavigationTransitions.swiftmodule/arm64-apple-ios.swiftmodule'
module with extension is not loaded (SwiftUIIntrospect)
```

If i switch back to version [0.9.3] everything works again.

Can you help?

**Comment by davdroman** [comment]
Thanks for the report. Have you tried deleting `DerivedData` and trying again? An underlying dependency module (SwiftUIIntrospect) has changed from 0.9.3 to 0.10.0 so there might be some bug that makes SPM confused about it.

**Comment by iTarek** [comment]
I tried everything
Restart the XCode, the Mac
Delete the DerivedData
Reset SPM cache
Even

https://stackoverflow.com/questions/72788019/where-is-swift-package-manager-cache-located-swift-5-7/72838880#72838880

**Comment by iTarek** [comment]
Why you closed the issue, are you sure this is not a general case, or bug in your last version?

**Comment by davdroman** [comment]
@iTarek okay thanks for checking. It sounds like it's on the library's side. I'll try to reproduce it, unless you have a sample project you can share with me to help me reproduce it?

**Comment by iTarek** [comment]
@davdroman I am sorry I don't have have a sample project. But it's easy just try to archive any project uses your lib. I can make a new project and test that for you and then share it if you want.

**Comment by davdroman** [comment]
@iTarek no problem. I'm on macOS Sonoma so I gotta re-download Xcode 14.3 which might take a while but hopefully will be able to reproduce it myself shortly.

**Comment by davdroman** [comment]
@iTarek that should do it. Give 0.10.1 a try :)
